version: "2"
linters:
  default: none
  enable:
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - testifylint
    - errcheck
    - goconst
    - errorlint
    - nilerr
    - whitespace
    - godot
    - nolintlint
    - makezero
    - perfsprint
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - performance
        - style
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - revive
          - unparam
          - unused
        path: _test\.go$
        text: unused-parameter
    paths:
      - vendor
      - third_party$
      - builtin$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$